default_agent: lautech_assistant
agents:
  lautech_assistant:
    name: lautech_assistant
    entrypoint: lautech_agentcore.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role_auto_create: true
      region: us-east-1
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    memory:
      mode: STM_ONLY
      event_expiry_days: 30
    identity:
      credential_providers: []
